service:
  proxy:
    image: nginx:stable-bookworm-perl
    ports:
      - "5000:5000"
  db:
    image: bitnami/postgresql:15.7.0-debian-12-r19
    ports:
      - "5432:5432"
  dotnet-runtime:
    image: bitnami/dotnet:8.0.7
#  aspnetcore-runtime:
#    image: bitnami/aspnet-core:8.0.7-debian-12-r4
